version: "3.8"

services:
  # container 1
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "4306:3306"
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpuser

    networks:
      - wpsite

  # container 2
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"

    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

    networks:
      - wpsite

  # container 3
  wordpress:
    depends_on:
      - db

    image: wordpress:latest

    volumes:
      - ./src/wp-content:/var/www/html/wp-content

    ports:
      - "8000:80"

    restart: always

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpuser
      WORDPRESS_DB_NAME: wordpress

    networks:
      - wpsite

networks:
  wpsite:

    null
volumes:
  db_data: {}
  src: {}